export const FILETREE_REQUEST_PENDING = 'APP/FILETREE_REQUEST_PENDING';
export const FILETREE_REQUEST_SUCCESS = 'APP/FILETREE_REQUEST_SUCCESS';
export const FILETREE_REQUEST_FAILED = 'APP/FILETREE_REQUEST_FAILED';

export const FILES_REQUEST_PENDING = 'APP/FILES_REQUEST_PENDING';
export const FILES_REQUEST_SUCCESS = 'APP/FILES_REQUEST_SUCCESS';
export const FILES_REQUEST_FAILED = 'APP/FILES_REQUEST_FAILED';

export const OPEN_TAB = 'APP/OPEN_TAB';
export const CLOSE_TAB = 'APP/CLOSE_TAB';

export const SET_FILE = 'APP/SET_FILE_STATE';
export const DELETE_FILE = 'APP/DELETE_FILE';
